server:
  port: 8765
spring:
  application:
    name: market-service
  data:
    mongodb:
      host: 10.0.0.14
      port: 27017
      database: rimi_oa
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://${eureka.instance.hostname}:${server.port}/swagger-ui.html
logging:
  file: "logs/market-service.log"
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS