server:
  port: 4000
spring:
  application:
    name: gateway-service
  redis:
    host: 10.0.0.14
    password:
    port: 6379
    database: 0
zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    search-service:
      path: /searchapi/**
      serviceId: search-service
      sensitiveHeaders: Cookie,Set-Cookie
    download-service:
      path: /downloadapi/**
      serviceId: download-service
      sensitiveHeaders: Cookie,Set-Cookie
    consultant-service:
      path: /consultantapi/**
      serviceId: consultant-service
      sensitiveHeaders: Cookie,Set-Cookie
    market-service:
      path: /marketapi/**
      serviceId: market-service
      sensitiveHeaders: Cookie,Set-Cookie
    user-service:
      path: /userapi/**
      serviceId: user-service
      sensitiveHeaders: Cookie,Set-Cookie
    customer-service:
      path: /customerapi/**
      serviceId: customer-service
      sensitiveHeaders: Cookie,Set-Cookie
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
logging:
  file: "logs/gateway-service.log"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS